name: Build and Deploy C++ Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y g++

    - name: Build C++ files
      run: |
        mkdir -p build
        for file in *.cpp; do
          if ! g++ -o "build/${file%.cpp}" "$file"; then
            echo "Failed to build $file"
            g++ -o "build/${file%.cpp}" "$file" 2>&1 | tee -a build_errors.log
          fi
        done

    - name: Push build results to another branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b build-branch
        git add build/ build_errors.log
        git commit -m "Add build results $(date)"
        git push --force origin build-branch